#!/bin/bash
set -e

## Adding some hues

infomsg (){
    tput setaf 2; tput bold; echo -e "\n\nHighlander Msg:"
    tput setaf 3; tput bold; echo -e "${1}\n\n"; tput sgr0
}
errormsg (){
    tput setaf 2; tput bold; echo -e "Highlander Msg:"
    tput setaf 1; tput bold; echo -e "${1}\n"; tput sgr0
}

infomsg "Script must be run with sudo / using a sudoer account."

sleep 1

## Adapted from:
##    https://gist.github.com/fernandoaleman/fe34e83781f222dfd8533b36a52dddcc

sudo yum -y update
sudo yum install -y epel-release

## install Erlang
##    Follow instructions to add repo, instructions in README here don't work
##    https://github.com/rabbitmq/erlang-rpm
##    Scripted the create here, but need to run this script as `sudo' now...
ERLANGREPOFILE="/etc/yum.repos.d/rabbitmq_erlang.repo"

cat >${ERLANGREPOFILE} <<EOL
[rabbitmq_erlang]
name=rabbitmq_erlang
baseurl=https://packagecloud.io/rabbitmq/erlang/el/7/\$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/rabbitmq/erlang/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300

[rabbitmq_erlang-source]
name=rabbitmq_erlang-source
baseurl=https://packagecloud.io/rabbitmq/erlang/el/7/SRPMS
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/rabbitmq/erlang/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
EOL

sudo chown root:root ${ERLANGREPOFILE}
sudo chmod 644 ${ERLANGREPOFILE}

## install Erlang dependencies
sudo yum install -y socat logrotate erlang

## installing RabbitMQ itself => skipping firewall instructions

wget https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.9/rabbitmq-server-3.7.9-1.el7.noarch.rpm
sudo rpm --import https://www.rabbitmq.com/rabbitmq-signing-key-public.asc
sudo rpm -Uvh rabbitmq-server-3.7.9-1.el7.noarch.rpm
rm rabbitmq-server-3.7.9-1.el7.noarch.rpm

sudo systemctl start rabbitmq-server
sudo systemctl enable rabbitmq-server

ADMINUSER="rabbitadmin"
ADMINPASS="password"
sudo rabbitmq-plugins enable rabbitmq_management
sudo chown -R rabbitmq:rabbitmq /var/lib/rabbitmq/
sudo rabbitmqctl add_user ${ADMINUSER} ${ADMINPASS}
sudo rabbitmqctl set_user_tags ${ADMINUSER} administrator
sudo rabbitmqctl set_permissions -p / ${ADMINUSER} ".*" ".*" ".*"

exit 0
