#!/bin/bash

set -e

## Single Demo Server for Chef

################# NOTES ###################

sudo yum upgrade -y
sudo yum install tree vim git -y ## Optional tools to make life easier
sudo yum install wget -y ## Not optional

infomsg (){
    tput setaf 2; tput bold; echo -e "\n\nHighlander Msg:"
    tput setaf 3; tput bold; echo -e "${1}\n\n"; tput sgr0
}
errormsg (){
    tput setaf 2; tput bold; echo -e "Highlander Msg:"
    tput setaf 1; tput bold; echo -e "${1}\n"; tput sgr0
}

## Tested on CentOS 7
## Source: https://docs.chef.io/install_server.html
## Verify ports on instance / server are open: https://docs.chef.io/server_firewalls_and_ports.html
## Intended for Demo use only
## Make sure to change # FIXME lines as needed
##

################# CHEF ###################
DEMOPATH="chef-pem-files"

mkdir -p ${DEMOPATH}

# Setting up the Chef user
 USERNAME="jaynecobb"      # FIXME
 FORENAME="Jayne"          # FIXME
 SURNAME="Cobb"            # FIXME
 EMAIL="vera@firefly.net"  # FIXME
 PASSWORD="chef-logzio"    # FIXME
 FILENAME="${DEMOPATH}/demo.pem"

# Setting up the Chef org
 SHORTNAME="firefly"       # FIXME
 ORGNAME="Firefly Logz"    # FIXME
 ASSOCUSER="${USERNAME}"
 ORGFILE="${DEMOPATH}/${SHORTNAME}-validator.pem"

CHEFVERSION="12.19.31"

infomsg "Installing Chef Stable release ${CHEFVERSION}.\nMid-way through you will be prompted to accept a license agreemnt."
sleep 2

# Base Chef server
sudo yum install wget -y

CHEFFILE="chef-server-core-${CHEFVERSION}-1.el7.x86_64.rpm"
wget https://packages.chef.io/files/stable/chef-server/${CHEFVERSION}/el/7/${CHEFFILE} -P /tmp/
sudo rpm -Uvh /tmp/${CHEFFILE}

infomsg "Running 'reconfigure', may take up to 5 minutes"
 sudo chef-server-ctl reconfigure
infomsg "Creating chef user ${USERNAME}"
 infomsg "sudo chef-server-ctl user-create ${USERNAME} ${FORENAME} ${SURNAME} ${EMAIL} '${PASSWORD}' --filename ${FILENAME}"
 sudo chef-server-ctl user-create ${USERNAME} ${FORENAME} ${SURNAME} ${EMAIL} '${PASSWORD}' --filename ${FILENAME}
infomsg "Creating chef org ${ORGNAME}"
 infomsg "sudo chef-server-ctl org-create ${SHORTNAME} '${ORGNAME}' --association_user ${ASSOCUSER} --filename ${ORGFILE}"
 sudo chef-server-ctl org-create ${SHORTNAME} '${ORGNAME}' --association_user ${ASSOCUSER} --filename ${ORGFILE}

# Chef Management Console (optional: if UI needed in demo)
 sudo chef-server-ctl install chef-manage
 sudo chef-server-ctl reconfigure
 sudo chef-manage-ctl reconfigure

infomsg "You now have a single Chef server."

