#!/bin/bash

set -e

## ELK Highlander : There Can Be Only One
## Single Demo Server for OSS ELK for Demo Purposes

################# NOTES ###################

sudo yum upgrade -y
sudo yum install tree vim git -y ## Optional tools to make life easier
sudo yum install wget -y ## Not optional

infomsg (){
    tput setaf 2; tput bold; echo -e "\n\nHighlander Msg:"
    tput setaf 3; tput bold; echo -e "${1}\n\n"; tput sgr0
}
errormsg (){
    tput setaf 2; tput bold; echo -e "Highlander Msg:"
    tput setaf 1; tput bold; echo -e "${1}\n"; tput sgr0
}

## Tested on CentOS 7
## Intended for Demo use only
## Make sure to change # FIXME lines as needed
##
## Elastic is consistent-ish with their naming conventions for past versions
## Please reference their page if you wish to download a different version
## than either of the two below:
##    https://www.elastic.co/downloads/past-releases/
ELKVERSION="7.2.0"
#ELKVERSION="6.5.4"

if [ -z ${ELKVERSION} ]; then
    errormsg "Please uncomment desired version before running script."
    exit 1
fi

################ FILEBEAT ##################
# Logzio SSL cert
sudo wget https://raw.githubusercontent.com/logzio/public-certificates/master/COMODORSADomainValidationSecureServerCA.crt -P /etc/pki/tls/certs/

FILE="filebeat-${ELKVERSION}-x86_64.rpm"
curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/${FILE}
sudo rpm -vi ${FILE}
sudo chkconfig --add filebeat
sudo mv /etc/filebeat/filebeat.yml{,.bkp}
sudo cp filebeat-demo.yml /etc/filebeat/filebeat.yml
sudo service filebeat start
filebeat version

rm ${FILE}


############# ELASTICSEARCH ################
infomsg "Starting Elasticsearch ${ELKVERSION} installation"
sleep 1

## Needed to add some logic because consistent naming is hard
if [ ${ELKVERSION} == "7.2.0" ]; then
    FILE="elasticsearch-${ELKVERSION}-x86_64.rpm"
else
    FILE="elasticsearch-${ELKVERSION}.rpm"
fi
echo "${FILE}"

## Install Java 8
sudo yum install java-1.8.0-openjdk.x86_64 -y
java -version

## Install elasticsearch itself
wget https://artifacts.elastic.co/downloads/elasticsearch/${FILE}
sudo rpm -ivh ${FILE}
sudo mv /etc/elasticsearch/elasticsearch.yml{,.bkp}
sudo cp elasticsearch-demo.yml /etc/elasticsearch/elasticsearch.yml
sudo systemctl enable elasticsearch.service
sudo service elasticsearch start
sudo service elasticsearch status
rm ${FILE}


############### LOGSTASH ##################
infomsg "Starting Logstash ${ELKVERSION} installation"
sleep 1

FILE="logstash-${ELKVERSION}.rpm"

wget https://artifacts.elastic.co/downloads/logstash/${FILE}
sudo rpm -ivh ${FILE}
sudo systemctl enable logstash.service
sudo service logstash start
sudo service logstash status
rm ${FILE}


################ KIBANA ##################
infomsg "Starting Kibana ${ELKVERSION} installation"
sleep 1

FILE="kibana-${ELKVERSION}-x86_64.rpm"

## Install Kibana itself
wget https://artifacts.elastic.co/downloads/kibana/${FILE}
sudo rpm -ivh ${FILE}
sudo mv /etc/kibana/kibana.yml{,.bkp}
sudo cp kibana-demo.yml /etc/kibana/kibana.yml
sudo systemctl enable kibana.service
sudo service kibana start
sudo service kibana status
rm ${FILE}

exit 0
